"""Mirror a .docx report as anchored Markdown (stdlib only: zipfile + ElementTree).

    python scripts/docx_to_md.py <path.docx> --out <dir>

Walks ``word/document.xml`` body in document order — paragraphs (with their
``pStyle``) and tables (rows joined with ``' | '``) — and writes:

    <out>/full.md          every block, paragraphs prefixed by a stable anchor
                           ``[p<8-hex sha1 of normalised text>]``; headings as
                           ``#`` / ``##`` (Heading1 / Heading2); captions verbatim
                           with their style tag; tables as Markdown rows
    <out>/frontmatter.md   everything before the first ``Chapter N`` Heading1
    <out>/ch<N>.md         one file per ``Chapter N`` Heading1
    <out>/references.md    from the heading matching /References/ to the end
    <out>/wordcount.json   per-chapter counts: (a) prose only, (b) prose + table
                           cells; headings, captions, front matter and
                           references are excluded from both

Read-only mirror of the source document: the tool never edits the .docx and
the source path is taken from the CLI only.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


def _w(tag: str) -> str:
    return f"{{{W_NS}}}{tag}"


HEADING_LEVELS: dict[str, int] = {
    "Title": 1,
    "Heading1": 1,
    "FrontMatterHeading": 1,
    "Heading2": 2,
    "Heading3": 3,
    "Heading4": 4,
}
CAPTION_STYLES: frozenset[str] = frozenset(
    {"Caption", "TableCaption", "CodeCaption", "FigureSubcaption", "TableSource"}
)
CHAPTER_RE = re.compile(r"^Chapter\s+(\d+)")
REFERENCES_RE = re.compile(r"References")
README_LINE = (
    "Generated by scripts/docx_to_md.py from the submitted draft "
    "(read-only mirror; do not edit)."
)


@dataclass
class Block:
    """One body-level block: a paragraph or a table."""

    kind: str  # "p" | "tbl"
    style: str = ""
    text: str = ""
    rows: list[list[str]] = field(default_factory=list)
    is_list: bool = False
    anchor: str = ""

    @property
    def is_heading(self) -> bool:
        return self.kind == "p" and self.style in HEADING_LEVELS

    @property
    def is_caption(self) -> bool:
        return self.kind == "p" and self.style in CAPTION_STYLES

    @property
    def is_prose(self) -> bool:
        return self.kind == "p" and not self.is_heading and not self.is_caption

    def word_count(self) -> int:
        if self.kind == "tbl":
            return sum(len(c.split()) for row in self.rows for c in row)
        return len(self.text.split())


# --------------------------------------------------------------------------- #
# Parsing
# --------------------------------------------------------------------------- #
def normalise(text: str) -> str:
    """Collapse whitespace so anchors survive re-flowing of the source."""
    return re.sub(r"\s+", " ", text).strip()


def anchor_for(text: str, prefix: str = "p") -> str:
    digest = hashlib.sha1(normalise(text).encode("utf-8")).hexdigest()[:8]
    return f"{prefix}{digest}"


def paragraph_text(p: ET.Element) -> str:
    """Concatenate run text, mapping tabs/breaks to spaces (tracked deletions skipped)."""
    parts: list[str] = []
    for el in p.iter():
        if el.tag == _w("t"):
            parts.append(el.text or "")
        elif el.tag in (_w("tab"), _w("br"), _w("cr")):
            parts.append(" ")
    return normalise("".join(parts))


def paragraph_style(p: ET.Element) -> str:
    ps = p.find(f"{_w('pPr')}/{_w('pStyle')}")
    return ps.get(_w("val"), "") if ps is not None else ""


def paragraph_is_list(p: ET.Element) -> bool:
    return p.find(f"{_w('pPr')}/{_w('numPr')}") is not None


def table_rows(tbl: ET.Element) -> list[list[str]]:
    rows: list[list[str]] = []
    for tr in tbl.findall(_w("tr")):
        cells: list[str] = []
        for tc in tr.findall(_w("tc")):
            cells.append(normalise(" ".join(paragraph_text(p) for p in tc.iter(_w("p")))))
        if any(cells):
            rows.append(cells)
    return rows


def iter_body_blocks(body: ET.Element) -> list[Block]:
    """Walk body children in order; descend into sdt wrappers; skip sectPr."""
    blocks: list[Block] = []

    def visit(container: ET.Element) -> None:
        for child in container:
            if child.tag == _w("p"):
                text = paragraph_text(child)
                if not text:
                    continue
                blocks.append(
                    Block(
                        kind="p",
                        style=paragraph_style(child),
                        text=text,
                        is_list=paragraph_is_list(child),
                    )
                )
            elif child.tag == _w("tbl"):
                rows = table_rows(child)
                if rows:
                    blocks.append(Block(kind="tbl", rows=rows))
            elif child.tag in (_w("sdt"), _w("sdtContent")):
                visit(child)
            elif child.tag == _w("sectPr"):
                continue

    visit(body)
    # stable anchors; duplicate texts get a numeric suffix so anchors stay unique
    seen: dict[str, int] = {}
    for b in blocks:
        base = (
            anchor_for(b.text)
            if b.kind == "p"
            else anchor_for(" | ".join(" | ".join(r) for r in b.rows), prefix="t")
        )
        n = seen.get(base, 0)
        seen[base] = n + 1
        b.anchor = base if n == 0 else f"{base}-{n + 1}"
    return blocks


def load_blocks(docx_path: Path) -> list[Block]:
    with zipfile.ZipFile(docx_path) as zf:
        root = ET.fromstring(zf.read("word/document.xml"))
    body = root.find(_w("body"))
    if body is None:
        raise SystemExit("no <w:body> in word/document.xml")
    return iter_body_blocks(body)


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #
def render_block(b: Block) -> list[str]:
    if b.kind == "tbl":
        lines = [f"[{b.anchor}]"]
        width = max(len(r) for r in b.rows)
        for i, row in enumerate(b.rows):
            cells = [c.replace("|", "\\|") for c in row] + [""] * (width - len(row))
            lines.append("| " + " | ".join(cells) + " |")
            if i == 0:
                lines.append("|" + "---|" * width)
        return lines
    if b.is_heading:
        return [f"{'#' * HEADING_LEVELS[b.style]} [{b.anchor}] {b.text}"]
    if b.is_caption or b.style == "Reference":
        return [f"[{b.anchor}] {{{b.style}}} {b.text}"]
    bullet = "- " if b.is_list else ""
    return [f"{bullet}[{b.anchor}] {b.text}"]


def render(blocks: list[Block]) -> str:
    out: list[str] = []
    for b in blocks:
        out.extend(render_block(b))
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# --------------------------------------------------------------------------- #
# Splitting + counting
# --------------------------------------------------------------------------- #
def split_sections(blocks: list[Block]) -> dict[str, list[Block]]:
    """Return {'frontmatter': [...], 'ch<N>': [...], 'references': [...]}."""
    sections: dict[str, list[Block]] = {"frontmatter": []}
    current = "frontmatter"
    for b in blocks:
        if b.is_heading and b.style in ("Heading1", "Title"):
            m = CHAPTER_RE.match(b.text)
            if m:
                current = f"ch{int(m.group(1))}"
                sections.setdefault(current, [])
            elif REFERENCES_RE.search(b.text) and "references" not in sections:
                current = "references"
                sections.setdefault(current, [])
        sections.setdefault(current, []).append(b)
    sections.setdefault("references", [])
    return sections


def word_counts(sections: dict[str, list[Block]]) -> dict:
    chapters: dict[str, dict] = {}
    for name in sorted(sections, key=lambda n: int(n[2:]) if n.startswith("ch") else -1):
        if not name.startswith("ch"):
            continue
        blocks = sections[name]
        prose = sum(b.word_count() for b in blocks if b.is_prose)
        tables = sum(b.word_count() for b in blocks if b.kind == "tbl")
        title = next((b.text for b in blocks if b.is_heading), "")
        chapters[name] = {
            "title": title,
            "prose_words": prose,
            "prose_plus_table_words": prose + tables,
            "table_words": tables,
            "n_paragraphs": sum(1 for b in blocks if b.is_prose),
            "n_tables": sum(1 for b in blocks if b.kind == "tbl"),
            "n_captions": sum(1 for b in blocks if b.is_caption),
        }
    return {
        "method": {
            "prose_words": "paragraph text split on whitespace; excludes headings, "
            "caption styles " + ", ".join(sorted(CAPTION_STYLES)) + ", table cells, "
            "front matter and references",
            "prose_plus_table_words": "prose_words plus every table cell",
        },
        "chapters": chapters,
        "totals": {
            "prose_words": sum(c["prose_words"] for c in chapters.values()),
            "prose_plus_table_words": sum(
                c["prose_plus_table_words"] for c in chapters.values()
            ),
        },
    }


def write_outputs(blocks: list[Block], out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "full.md").write_text(README_LINE + "\n\n" + render(blocks), encoding="utf-8")
    sections = split_sections(blocks)
    for name, sec in sections.items():
        (out_dir / f"{name}.md").write_text(render(sec) if sec else "", encoding="utf-8")
    counts = word_counts(sections)
    (out_dir / "wordcount.json").write_text(
        json.dumps(counts, indent=2) + "\n", encoding="utf-8"
    )
    return counts


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("docx", type=Path, help="source .docx (read-only)")
    ap.add_argument("--out", type=Path, required=True, help="output directory")
    args = ap.parse_args(argv)
    if not args.docx.is_file():
        print(f"not a file: {args.docx}", file=sys.stderr)
        return 2
    blocks = load_blocks(args.docx)
    counts = write_outputs(blocks, args.out)
    for name, c in counts["chapters"].items():
        print(f"{name}: prose={c['prose_words']} prose+tables={c['prose_plus_table_words']}")
    t = counts["totals"]
    print(f"TOTAL: prose={t['prose_words']} prose+tables={t['prose_plus_table_words']}")
    print(f"blocks={len(blocks)} -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
